grpc:
  addr: ":50052"

http:
  addr: ":8083"
  swagger_path: "./internal/pb/swagger/feed_api/feed.swagger.json"

database:
  host: "localhost"
  port: 55432
  username: "admin"
  password: "admin"
  name: "activity"
  ssl_mode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  topic_name: "user-actions"
  group_id: "feed-service-group"


